CREATE TABLE [dbo].[Users] (
	[Id] INT IDENTITY(1,1) PRIMARY KEY,
	[FullName] NVARCHAR(100) NOT NULL,
	[Email] NVARCHAR(256) NOT NULL UNIQUE,
	[PasswordHash] NVARCHAR(MAX) NOT NULL,
	[CreatedAt] DATETIME2 DEFAULT SYSUTCDATETIME()
);